### ISSUE TITLE
Alphabetical Order

### ISSUE THREAD

**Issue by derek-skinner** [stevekinney/pizza#51]
This list would be way more helpful and organized if it was arranged in alphabetical order by city name. I'll try to do this as soon as I can, if no one else gets to it first.

**Comment by mikedao** [comment]
I've already reorganized it so it is broken up by country, and then alphabetical by state, and then alphabetical by city. I think it's more useful that people can view by state as a group rather than city alphabetically. Example, a person in NYC can, at a glance, view pizza places in both Brooklyn and NYC.

**Comment by derek-skinner** [comment]
Ahh gotcha. That makes sense. Thanks for clarifying the organizational system.
